"""Kiến thức tiếng Việt viết tay để mô hình nghĩa (e5) có thêm ví dụ về những cách nói CHƯA có trong train/validation.

Tất cả được viết từ hiểu biết ngôn ngữ chung, KHÔNG lấy từ nội dung test.
"""

# 0 trung tính, 1 gấp, 2 dễ vỡ, 3 không gấp, 4 không dễ vỡ
PHRASES = {
    1: ["gấp lắm", "việc gấp", "khẩn cấp", "rất khẩn", "cần ngay", "giao ngay lập tức", "đi ngay nhé", "làm ngay đi",
        "càng sớm càng tốt", "càng nhanh càng tốt", "đừng chậm trễ", "không được chậm trễ", "không được trễ", "ưu tiên hàng đầu",
        "ưu tiên số một", "ưu tiên cao nhất", "hỏa tốc", "đơn hỏa tốc", "nhanh lên nhé", "nhanh nhất có thể", "khẩn trương lên",
        "khẩn trương giúp mình", "cấp tốc", "tức tốc", "sắp trễ rồi", "kẻo trễ", "kẻo muộn", "người nhận đang chờ gấp",
        "đang rất cần", "đang cần gấp", "phải tới trong vài phút nữa", "cần trong năm phút", "trong vòng mười phút", "giao liền nhé",
        "không thể chậm hơn", "thời gian rất gấp", "đang vội lắm", "rất vội", "chạy nhanh giúp mình", "việc này không chờ được",
        "hạn chót sắp đến", "cần kíp", "lẹ lên nhé", "đi lẹ giúp", "phải kịp trước giờ", "đừng để lâu", "không được để chờ lâu",
        "ưu tiên đơn này trước", "xử lý ngay", "giao hỏa tốc", "gấp gáp lắm", "cần gấp trong hôm nay ngay bây giờ",
        "không thể chờ thêm", "đừng để người nhận chờ", "chậm là không kịp", "không nhanh là trễ", "phải có mặt ngay",
        "việc này rất gấp", "đơn khẩn", "đơn gấp", "người ta đang hối", "bên kia đang giục", "cần liền", "nhanh nhanh giúp",
        "thời gian không còn nhiều", "sát giờ rồi", "đang chờ từng phút", "càng lẹ càng tốt", "đi liền nha",
        # (bổ sung 2026-10-03: thêm các kiểu nói gấp theo hạn giờ, thúc giục, tốc độ)
        "phải xong trước 9 giờ", "trước 10 giờ phải có", "hạn chót là 15 phút nữa", "còn 5 phút nữa thôi", "chỉ còn ít phút",
        "sắp đến giờ rồi", "sắp vào lớp rồi", "sắp bắt đầu rồi", "buổi họp sắp bắt đầu", "sắp hết giờ", "sắp hết hạn",
        "deadline tới nơi rồi", "đang chạy deadline", "trễ giờ mất", "muộn giờ mất rồi", "cho kịp giờ", "phải kịp giờ học",
        "người nhận đang đợi sẵn", "bên nhận đang đứng chờ", "đang ngóng từng giây", "đang sốt ruột chờ", "đang nóng ruột lắm",
        "bị giục nãy giờ", "sếp đang hối", "thầy đang chờ gấp", "bệnh nhân đang chờ", "ca cấp cứu đang chờ",
        "nước sôi lửa bỏng", "cháy tới nơi rồi", "chuyện gấp như cứu hỏa", "tình huống khẩn", "trường hợp khẩn cấp",
        "giao tốc hành", "giao siêu tốc", "giao thần tốc", "đi hết tốc lực", "chạy hết tốc lực", "phóng nhanh giúp",
        "đi đường nhanh nhất", "chọn đường ngắn nhất cho nhanh", "đừng la cà", "đừng dừng dọc đường", "đi thẳng một mạch",
        "tranh thủ giúp mình", "tranh thủ từng phút", "ngay tức khắc", "tức khắc", "cấp kỳ", "liền tay giúp", "làm liền",
        "ASAP nhé", "express nhé", "không được phép chậm", "chậm một phút cũng không được", "một giây cũng quý",
        "không có thời gian đâu", "hết thời gian rồi", "thời gian là vàng lúc này", "mau lên", "mau mau giúp", "lẹ lẹ giùm",
        "nhanh chân lên", "khẩn thiết", "bức thiết lắm", "cần gấp gáp", "đơn ưu tiên", "ưu tiên xử lý trước"],
    3: ["không gấp", "không gấp đâu", "không vội", "không cần vội", "cứ từ từ", "cứ thong thả", "thong thả thôi", "lúc nào giao cũng được",
        "khi nào giao cũng được", "mai giao cũng được", "mai giao cũng kịp", "chiều nay giao cũng được", "khi nào rảnh thì giao",
        "tiện lúc nào thì giao", "không cần nhanh", "chậm một chút cũng được", "không có gì gấp", "không cần ưu tiên", "bao giờ tới cũng được",
        "đi thong thả", "không phải vội", "chưa cần ngay", "để sau cũng được", "thời gian thoải mái", "không hạn chót", "từ từ mà đi",
        "khỏi cần vội", "không việc gì phải gấp", "trễ một chút không sao", "muộn cũng không sao", "tối giao cũng kịp", "tuần sau cũng được",
        "chẳng có gì phải vội", "gấp gì đâu", "đâu cần nhanh", "khỏi phải khẩn trương", "chưa cần gấp", "không cần phải ngay",
        "chẳng gấp gáp gì", "thư thả mà đi", "không ai hối đâu", "đơn thường thôi", "không ưu tiên gì", "cứ bình tĩnh",
        "nhàn nhã thôi", "lúc nào tiện thì đi", "không cần khẩn trương", "đâu có gấp", "vội gì đâu", "còn nhiều thời gian",
        "trong ngày là được", "trong tuần là được", "cuối ngày giao cũng ổn", "hôm nào giao cũng được", "không giới hạn thời gian",
        "không có deadline", "hạn còn xa", "còn dư dả thời gian", "không ai chờ đâu", "người nhận không vội", "đi chậm cũng được",
        "không cần chạy nhanh", "cứ đi bình thường", "tốc độ bình thường là được", "đơn không ưu tiên", "xếp sau các đơn khác cũng được",
        "rảnh thì làm", "tiện đường thì ghé", "ung dung mà đi", "thoải mái thời gian", "không phải hỏa tốc", "không khẩn cấp",
        "chẳng cần hối", "đâu ai giục", "trễ chút cũng chẳng sao", "tối nay hay mai đều được"],
    2: ["hàng dễ vỡ", "đồ dễ vỡ", "dễ vỡ lắm", "bên trong là đồ thủy tinh", "đồ thủy tinh", "đồ gốm sứ", "đồ gốm bên trong", "đồ sứ",
        "nhẹ tay giúp", "nhẹ tay nhé", "xin nhẹ nhàng", "cẩn thận kẻo vỡ", "đi cẩn thận", "hàng mỏng manh", "kiện hàng mỏng manh",
        "tránh va đập", "tránh va chạm", "kỵ va đập", "kỵ rung lắc", "tránh rung lắc", "dễ hỏng khi va đập", "dễ hỏng", "đừng làm rơi",
        "không được làm rơi", "hàng cần nâng niu", "dễ nứt", "dễ bể", "dễ móp", "đồ pha lê", "bên trong có chai lọ", "thiết bị nhạy cảm",
        "linh kiện dễ hỏng", "không được va chạm mạnh", "cầm cẩn thận", "hàng cần nhẹ tay", "chú ý hàng dễ vỡ", "xin đừng lắc mạnh",
        "đồ rất dễ vỡ", "có đồ thủy tinh bên trong", "hàng dễ bị vỡ", "hàng yếu, đi êm thôi", "đi êm giúp mình", "giữ thăng bằng kẻo đổ vỡ",
        "màn hình dễ nứt", "đồ điện tử nhạy cảm", "không chịu được va đập", "không được quăng ném", "đừng xóc mạnh",
        "hàng dễ vỡ xin nhẹ tay", "coi chừng vỡ", "kẻo vỡ", "vỡ là hỏng hết", "đồ dễ gãy", "hàng dễ dập", "chứa đồ thủy tinh",
        "đồ sành sứ", "ly tách bên trong", "bóng đèn bên trong", "hàng nhạy cảm với va chạm", "xin giữ nhẹ nhàng", "nâng như nâng trứng"],
    4: ["không dễ vỡ", "hàng chắc chắn", "hàng chắc chắn, không dễ vỡ", "rơi cũng không sao", "rơi cũng chẳng sao", "đồ bền",
        "hàng bền, không lo vỡ", "không sợ va đập", "không lo vỡ", "đồ không vỡ được", "hàng cứng cáp", "không cần nhẹ tay",
        "va đập thoải mái", "không sợ rơi", "chắc lắm không vỡ đâu", "đồ nhựa cứng không vỡ", "không có gì dễ vỡ", "hàng không dễ hỏng",
        "khó vỡ lắm", "không mỏng manh", "cứ mạnh tay", "không cần cẩn thận quá", "đồ vải không sợ rơi", "hàng không kỵ va đập",
        "vỡ sao được", "chẳng dễ vỡ đâu", "không phải hàng dễ vỡ", "rơi vỡ gì đâu", "không cần nâng niu", "đâu có dễ vỡ",
        "đồ này lì lắm", "quăng cũng không sao", "va chạm cũng chẳng hề gì", "không sợ móp", "hàng khô không vỡ", "toàn giấy tờ không vỡ được"],
    0: ["cảm ơn", "cảm ơn nhiều", "cảm ơn bạn", "cảm ơn robot", "thanks robot", "xin chào", "chào robot", "robot ơi", "nhờ bạn nhé",
        "yêu cầu mới", "nhắn robot", "chúc một ngày tốt lành", "hẹn gặp lại", "phiền bạn nhé", "nhờ cả vào bạn", "làm tốt lắm",
        "đơn mới đây", "có việc nhờ đây", "xin nhờ một việc", "vậy nhé", "thế nhé", "trân trọng"],
}

# cách gọi khác của từng loại địa điểm
PLACES = {
    "library": ["thư viện", "thư viện trường", "phòng đọc", "khu đọc sách", "nơi mượn sách", "chỗ trả sách", "kho sách", "phòng sách",
                "trung tâm học liệu", "phòng tư liệu", "phòng tài liệu", "nơi tra cứu tài liệu", "quầy mượn trả sách", "tủ sách chung",
                "phòng báo chí", "nơi đọc sách", "thủ thư", "cán bộ thư viện", "quầy thủ thư"],
    "dorm": ["ký túc xá", "ktx", "khu ký túc", "khu nội trú", "nhà ở sinh viên", "khu ở của sinh viên", "phòng ở sinh viên", "khu lưu trú",
             "cư xá sinh viên", "dãy phòng nội trú", "nơi sinh viên ở", "làng sinh viên", "khu nhà ở", "phòng ngủ sinh viên", "khu phòng trọ sinh viên",
             "nhà nghỉ sinh viên", "ban quản lý ký túc xá", "sinh viên nội trú", "quản lý ký túc"],
    "sports": ["nhà thể thao", "nhà thi đấu", "khu thể thao", "sân thể thao", "sân bóng", "sân tập", "nhà thể chất", "phòng tập", "phòng gym",
               "khu vận động", "sân luyện tập", "nhà đa năng", "sân vận động", "sân cầu lông", "sân bóng rổ", "bể bơi", "khu thể dục",
               "nơi tập thể dục", "huấn luyện viên", "đội bóng", "câu lạc bộ thể thao", "sân chơi thể thao"],
    "clinic": ["trạm y tế", "phòng y tế", "trạm xá", "phòng khám", "phòng khám của trường", "phòng sơ cứu", "khu y tế", "nơi khám sức khỏe",
               "phòng bác sĩ", "bệnh xá", "phòng cấp cứu", "phòng điều dưỡng", "phòng thuốc", "quầy thuốc", "nơi chăm sóc sức khỏe",
               "bác sĩ trường", "y tá trực", "nhân viên y tế", "phòng khám bệnh"],
    "canteen": ["căn tin", "căng tin", "canteen", "nhà ăn", "bếp ăn", "khu ăn uống", "phòng ăn", "phòng ăn tập thể", "quán ăn sinh viên",
                "khu ẩm thực", "nơi phục vụ bữa trưa", "quầy ăn", "nhà bếp", "quầy đồ ăn", "nơi ăn trưa", "quán cà phê trong trường",
                "bếp trưởng", "cô cấp dưỡng", "nhân viên quầy ăn", "quầy giải khát"],
    "parking": ["bãi xe", "bãi đỗ xe", "bãi gửi xe", "nhà xe", "hầm xe", "khu gửi xe", "chỗ để xe", "nơi giữ xe", "khu đậu xe", "bãi đậu xe",
                "bãi giữ xe", "nhà để xe", "ga ra", "bãi xe máy", "bãi ô tô", "điểm trông xe", "bác giữ xe", "nhân viên trông xe", "chỗ gửi xe đạp"],
    "lecture": ["giảng đường", "tòa giảng đường", "khu giảng đường", "phòng học", "phòng học lớn", "lớp học", "hội trường học", "dãy phòng học",
                "nơi lên lớp", "nhà học", "tòa nhà học", "khu lớp học", "phòng giảng", "hội trường", "nơi nghe giảng", "giảng viên đang dạy",
                "lớp trưởng", "cán sự lớp", "phòng học lý thuyết"],
    "lab": ["phòng thí nghiệm", "phòng lab", "lab hóa", "khu thí nghiệm", "phòng thực hành", "xưởng thực hành", "phòng thực nghiệm",
            "nơi làm thí nghiệm", "phòng nghiên cứu", "trung tâm thí nghiệm", "xưởng thực tập", "phòng máy thực hành", "phòng lab sinh học",
            "kỹ thuật viên phòng lab", "nhóm nghiên cứu", "người hướng dẫn thực hành", "phòng thí nghiệm vật lý"],
    "office": ["phòng hành chính", "khu hành chính", "văn phòng khoa", "phòng đào tạo", "phòng một cửa", "tòa hiệu bộ", "phòng giáo vụ",
               "nơi nộp hồ sơ", "văn phòng", "phòng công tác sinh viên", "phòng tài vụ", "phòng kế toán", "phòng tổ chức", "văn thư",
               "ban giám hiệu", "phòng tuyển sinh", "phòng khảo thí", "nơi làm thủ tục", "thư ký khoa", "chuyên viên một cửa", "cán bộ phòng đào tạo"],
    "gate": ["cổng trường", "cổng chính", "cổng vào", "cổng a", "lối vào trường", "chốt bảo vệ cổng", "chốt cổng", "nơi khách đến trường",
             "cổng phụ", "cổng sau", "cửa vào trường", "trạm gác", "phòng bảo vệ", "chốt gác", "lối ra vào", "nơi đón khách", "bảo vệ cổng",
             "tổ đón khách", "nhân viên trực cổng", "quầy lễ tân cổng"],
}

# ---- Bổ sung 2026-10-06: thêm nhiều cách gọi địa điểm và người làm việc ở đó (kiến thức tiếng Việt chung, KHÔNG lấy từ test)
PLACES_MORE = {
    "library": ["thư viện trung tâm", "thư viện khoa", "thư viện điện tử", "phòng đọc sách", "phòng đọc tự chọn", "phòng đọc chung",
                "khu tự học", "phòng tự học", "góc đọc sách", "trung tâm thông tin thư viện", "trung tâm tư liệu", "kho tài liệu",
                "kho giáo trình", "quầy mượn sách", "quầy trả sách", "nơi trả sách", "chỗ mượn sách", "chỗ đọc sách", "nhà sách trường",
                "phòng lưu trữ sách", "khu sách tham khảo", "nơi mượn tài liệu", "nơi tra cứu sách", "phòng đọc báo", "phòng luận văn",
                "nhân viên thư viện", "cô thủ thư", "chú thủ thư", "bạn trực thư viện", "người quản lý thư viện", "ban thư viện",
                "học liệu", "trung tâm học liệu số", "quầy sách", "giá sách chung", "nơi giữ sách", "phòng đọc yên tĩnh"],
    "dorm": ["ký túc xá sinh viên", "khu ký túc xá", "tòa ký túc", "nhà ký túc", "dãy ký túc", "khu nhà ở sinh viên", "nhà ở nội trú",
             "khu nội trú sinh viên", "phòng nội trú", "chỗ ở sinh viên", "nơi ở của sinh viên", "khu ở", "nhà tập thể sinh viên",
             "khu tập thể", "dãy nhà ở", "tòa nhà ở", "khu lưu xá", "lưu xá", "ký túc", "phòng ký túc", "khu phòng ở", "nơi ngủ nghỉ",
             "chỗ ngủ của sinh viên", "khu cư trú sinh viên", "nhà khách sinh viên", "khu ở nội trú", "căn hộ sinh viên",
             "trưởng ký túc xá", "quản lý nội trú", "cô quản lý ký túc", "bác trực ký túc", "sinh viên ở ký túc", "ban nội trú",
             "tự quản ký túc xá", "phòng quản lý ký túc", "nhà nội trú"],
    "sports": ["nhà thi đấu đa năng", "nhà tập thể thao", "nhà luyện tập", "sân thể dục", "sân điền kinh", "sân bóng đá", "sân bóng chuyền",
               "sân bóng bàn", "sân quần vợt", "sân tennis", "bể bơi trường", "hồ bơi", "phòng thể hình", "phòng tập thể lực",
               "khu rèn luyện thể chất", "khu thể chất", "trung tâm thể thao", "trung tâm giáo dục thể chất", "khu tập luyện",
               "sân tập luyện", "phòng tập võ", "câu lạc bộ võ thuật", "nhà tập", "sân cỏ", "sân cỏ nhân tạo", "khu thể dục thể thao",
               "thầy thể dục", "giáo viên thể chất", "huấn luyện viên đội tuyển", "đội tuyển bóng", "vận động viên", "câu lạc bộ bóng đá",
               "trọng tài", "phòng dụng cụ thể thao", "kho dụng cụ thể thao", "đường chạy", "khán đài"],
    "clinic": ["trạm y tế trường", "phòng y tế trường", "phòng khám đa khoa", "phòng khám sức khỏe", "khu khám bệnh", "nơi khám bệnh",
               "phòng sơ cứu ban đầu", "trung tâm y tế", "y tế học đường", "phòng y vụ", "bệnh xá trường", "phòng điều trị",
               "phòng tiêm", "phòng phát thuốc", "quầy phát thuốc", "nhà thuốc trường", "phòng chăm sóc sức khỏe", "phòng cấp cứu nhỏ",
               "bác sĩ trực", "y tá trường", "điều dưỡng trực", "cô y tá", "nhân viên y tế trường", "cán bộ y tế", "dược sĩ",
               "phòng khám nha", "phòng khám mắt", "phòng nghỉ cho người ốm", "nơi chữa bệnh", "khu chăm sóc y tế", "phòng bác sĩ trực"],
    "canteen": ["căng tin trường", "căn tin sinh viên", "nhà ăn sinh viên", "nhà ăn tập thể", "bếp ăn tập thể", "bếp ăn sinh viên",
                "khu ẩm thực sinh viên", "khu ăn uống sinh viên", "quầy cơm", "quán cơm", "quán ăn", "quầy ăn uống", "phòng ăn sinh viên",
                "nơi ăn uống", "chỗ ăn trưa", "chỗ ăn cơm", "nơi bán đồ ăn", "quầy bán đồ ăn", "quầy nước", "quán nước", "quán cà phê",
                "quầy cà phê", "khu food court", "nhà bếp trường", "bếp trường", "đầu bếp", "cô nấu ăn", "cô bán cơm", "chị bán hàng căng tin",
                "nhân viên nhà ăn", "nhân viên bếp", "ban quản lý nhà ăn", "quầy đồ uống", "nơi phục vụ bữa ăn", "nơi phát cơm"],
    "parking": ["bãi giữ xe sinh viên", "bãi để xe", "bãi xe trường", "nhà giữ xe", "nhà để xe sinh viên", "khu để xe", "khu để xe máy",
                "khu đỗ xe", "chỗ đỗ xe", "chỗ đậu xe", "chỗ giữ xe", "nơi để xe", "nơi đỗ xe", "nơi gửi xe", "hầm gửi xe", "hầm để xe",
                "tầng hầm để xe", "bãi xe đạp", "bãi đỗ ô tô", "điểm giữ xe", "trạm giữ xe", "chòi giữ xe", "chú giữ xe", "cô giữ xe",
                "bảo vệ bãi xe", "người trông xe", "nhân viên giữ xe", "quầy vé xe", "khu xe máy", "nhà xe sinh viên"],
    "lecture": ["giảng đường lớn", "giảng đường chính", "tòa giảng đường chính", "nhà giảng đường", "khu nhà học", "khu học tập",
                "dãy nhà học", "dãy lớp học", "phòng học chung", "phòng học số", "lớp", "phòng lý thuyết", "hội trường lớn",
                "phòng hội thảo", "phòng seminar", "nơi học", "chỗ học", "tòa học", "nhà học chính", "khu lớp", "phòng chuyên đề",
                "thầy đang giảng", "cô giáo đang dạy", "giảng viên đứng lớp", "thầy giáo", "cô giáo", "lớp phó", "bí thư lớp",
                "sinh viên trong lớp", "nhóm học tập", "phòng thi", "khu phòng thi", "phòng học tầng hai"],
    "lab": ["phòng thí nghiệm hóa", "phòng thí nghiệm sinh", "phòng thí nghiệm điện", "phòng thí nghiệm cơ khí", "phòng lab máy tính",
            "phòng máy", "phòng máy tính", "phòng thực hành máy", "phòng thực hành điện", "xưởng cơ khí", "xưởng điện", "xưởng chế tạo",
            "khu thực hành", "trung tâm thực hành", "trung tâm nghiên cứu", "viện nghiên cứu", "phòng nghiên cứu khoa học",
            "phòng R&D", "phòng chế tạo", "phòng robot", "lab nghiên cứu", "lab robot", "lab điện tử", "lab sinh học", "lab vật lý",
            "nghiên cứu viên", "trợ giảng thực hành", "kỹ sư phòng lab", "nhóm thí nghiệm", "cán bộ phòng thí nghiệm",
            "thầy hướng dẫn thí nghiệm", "người phụ trách lab", "kho hóa chất", "phòng thí nghiệm trọng điểm"],
    "office": ["văn phòng trường", "văn phòng khoa", "văn phòng bộ môn", "phòng hành chính tổng hợp", "phòng tổ chức hành chính",
               "phòng quản lý đào tạo", "phòng công tác học sinh sinh viên", "phòng kế hoạch tài chính", "phòng tài chính", "phòng nhân sự",
               "phòng quản trị", "phòng thanh tra", "phòng hợp tác quốc tế", "phòng khoa học", "ban giám đốc", "phòng hiệu trưởng",
               "phòng hiệu phó", "nhà điều hành", "tòa điều hành", "tòa hành chính", "khu văn phòng", "bộ phận một cửa",
               "quầy một cửa", "trung tâm một cửa", "nơi nhận hồ sơ", "nơi giải quyết thủ tục", "chỗ nộp giấy tờ", "phòng văn thư",
               "cô văn thư", "chị giáo vụ", "thầy giáo vụ", "chuyên viên đào tạo", "trợ lý khoa", "thư ký", "kế toán trường",
               "thủ quỹ", "trưởng phòng hành chính", "cán bộ hành chính", "phòng tiếp nhận hồ sơ", "phòng đào tạo sau đại học"],
    "gate": ["cổng chính trường", "cổng trước", "cổng phía trước", "cổng số một", "cổng số hai", "cổng b", "cổng phụ trường",
             "cổng ra vào", "lối vào chính", "lối ra", "cửa ngõ trường", "cửa chính", "chốt bảo vệ", "phòng bảo vệ cổng", "trạm bảo vệ",
             "bốt bảo vệ", "chốt gác cổng", "nơi đón tiếp khách", "khu đón khách", "sảnh đón khách", "quầy tiếp đón", "quầy lễ tân",
             "nơi khách vào", "nơi khách ra vào", "chú bảo vệ", "anh bảo vệ", "bác bảo vệ", "đội bảo vệ", "nhân viên bảo vệ",
             "tổ bảo vệ", "người gác cổng", "lễ tân", "nhân viên lễ tân", "barie cổng", "cổng sau trường"],
}

# ---- Bổ sung 2026-10-04: thêm nhiều cách nói cho cả 5 lớp (kiến thức tiếng Việt chung, KHÔNG lấy từ test) ----
# Mục đích: mô hình nghĩa phân biệt được "gấp" với "không gấp / thong thả" và với câu trung tính ở những cách nói chưa gặp.
PHRASES_MORE = {
    1: ["giao gấp giúp mình", "mình cần gấp", "em cần gấp lắm ạ", "gấp quá rồi", "rất gấp", "cực kỳ gấp", "gấp lắm rồi đó",
        "việc này gấp", "đơn này gấp", "chuyện gấp", "cần gấp trong buổi sáng", "gấp không chờ được", "cần ngay bây giờ",
        "cần ngay lập tức", "giao ngay giúp", "đi ngay giúp mình", "xuất phát ngay", "lên đường ngay", "làm ngay giúp",
        "ngay và luôn", "ngay tức thì", "lập tức lên đường", "khẩn cấp lắm", "khẩn lắm", "rất khẩn cấp", "việc khẩn",
        "tình hình khẩn cấp", "khẩn trương nhé", "khẩn trương lên nào", "nhanh lên giúp mình", "nhanh nhất có thể nhé",
        "càng sớm càng tốt nhé", "sớm nhất có thể", "trong thời gian sớm nhất", "thật nhanh giúp mình", "nhanh hết mức",
        "đừng chậm trễ nhé", "không được chậm", "không được muộn", "không được đến trễ", "chậm là hỏng việc",
        "trễ là hỏng hết", "muộn là không kịp", "không kịp mất", "sợ không kịp", "phải kịp trước buổi học", "kịp giờ họp nhé",
        "còn mười phút nữa là vào học", "còn ít phút nữa thôi", "chỉ còn vài phút", "trong vòng năm phút", "trong ít phút tới",
        "năm phút nữa phải có", "mười phút nữa cần dùng", "sắp tới giờ rồi", "sắp vào tiết", "sắp họp rồi", "sắp thi rồi",
        "người nhận đang cần gấp", "người nhận đang đợi", "bên kia đang đợi", "đang đợi ngoài cửa", "đang chờ sẵn ở đó",
        "đang ngóng lắm", "đang sốt ruột lắm", "nóng ruột chờ", "bị hối suốt", "sếp giục rồi", "thầy đang giục",
        "ưu tiên cao", "ưu tiên gấp", "ưu tiên trước hết", "ưu tiên hàng đầu nhé", "làm trước các đơn khác", "đẩy đơn này lên trước",
        "hỏa tốc nhé", "giao hỏa tốc giúp", "chuyển phát hỏa tốc", "giao nhanh giúp mình", "giao lẹ giúp", "lẹ lên", "mau lên nhé",
        "đi mau giúp", "chạy nhanh lên", "tăng tốc lên", "hết sức khẩn trương", "không có thời gian chờ", "không chờ lâu được",
        "không thể đợi", "đợi lâu không được", "thời gian gấp rút", "gấp rút lắm", "cấp bách", "việc cấp bách", "rất cấp thiết",
        "cần kíp lắm", "nước đến chân rồi", "sát nút rồi", "trễ lắm rồi", "muộn lắm rồi", "đã trễ rồi nhanh lên",
        "time gấp", "urgent nhé", "cần urgent", "đơn urgent", "giao liền giúp", "giao luôn và ngay", "cần liền bây giờ"],
    3: ["không gấp nhé", "không gấp gì", "không gấp lắm", "chưa gấp", "chưa gấp đâu", "chẳng gấp", "chả gấp gì", "đâu có gì gấp",
        "không vội đâu", "không vội gì", "chưa vội", "đừng vội", "đừng vội vàng", "đừng gấp", "khỏi vội", "không phải gấp đâu",
        "cứ từ từ nhé", "cứ từ từ mà làm", "từ từ thôi", "từ từ cũng được", "thong thả nhé", "cứ thong thả mà đi", "thư thả thôi",
        "thoải mái đi", "cứ thoải mái", "thoải mái thời gian nhé", "lúc nào cũng được", "khi nào cũng được", "bao giờ cũng được",
        "hôm nay hay mai đều được", "mai cũng được", "mai giao cũng không sao", "ngày mai giao cũng được", "tối giao cũng được",
        "chiều giao cũng được", "cuối giờ giao cũng được", "cuối tuần giao cũng được", "tuần này giao là được", "trong hôm nay là được",
        "khi nào tiện thì giao", "lúc nào rảnh thì mang qua", "rảnh thì giao", "tiện thì làm", "tiện lúc nào giao lúc đó",
        "không cần nhanh đâu", "không cần đi nhanh", "không cần giao ngay", "không cần ngay đâu", "chưa cần ngay", "chưa cần gấp đâu",
        "chưa cần tới ngay", "không cần ưu tiên đâu", "không cần hỏa tốc", "không cần khẩn trương đâu", "chẳng cần vội",
        "trễ chút cũng được", "trễ một chút không sao đâu", "muộn chút không sao", "muộn một chút cũng được", "chậm chút không sao",
        "đi chậm thôi cũng được", "chậm mà chắc", "không ai chờ cả", "không ai đợi đâu", "người nhận không gấp", "người nhận chưa cần",
        "bên nhận không vội", "không có hạn chót", "không có hạn giờ", "không giới hạn giờ giấc", "còn dư thời gian",
        "còn nhiều thì giờ", "thời gian còn dài", "thời gian thoải mái lắm", "đơn thường", "đơn bình thường thôi", "ưu tiên thấp",
        "mức ưu tiên thấp", "xếp sau cũng được", "làm sau cũng được", "để sau cũng không sao", "để lúc khác cũng được",
        "bình tĩnh mà đi", "cứ bình tĩnh nhé", "đi bình thường thôi", "tốc độ thường thôi", "nhẩn nha cũng được", "ung dung thôi",
        "không việc gì phải vội", "vội làm gì", "gấp gáp gì đâu", "có gì đâu mà gấp", "không đến mức gấp", "không quá gấp",
        "hết gấp rồi", "không còn gấp nữa", "giờ thì không gấp nữa", "no rush nhé", "không rush"],
    2: ["dễ vỡ nhé", "hàng dễ vỡ nhé", "đồ dễ vỡ đó", "rất dễ vỡ", "cực kỳ dễ vỡ", "dễ vỡ xin cẩn thận", "cẩn thận dễ vỡ",
        "hàng thủy tinh", "bên trong có thủy tinh", "có đồ thủy tinh", "chai thủy tinh bên trong", "lọ thủy tinh", "cốc thủy tinh",
        "bình thủy tinh", "ống nghiệm thủy tinh", "đồ gốm", "bình gốm", "đồ sứ dễ vỡ", "bát đĩa sứ", "chén sứ", "đồ pha lê dễ vỡ",
        "hàng mỏng manh lắm", "đồ mỏng manh", "rất mỏng manh", "hàng dễ hỏng", "dễ hỏng lắm", "dễ hư hỏng", "dễ hư", "dễ bể lắm",
        "dễ nứt vỡ", "dễ móp méo", "dễ gãy", "dễ trầy xước", "hàng dễ dập nát", "tránh va đập mạnh", "tránh va chạm mạnh",
        "tránh rung lắc mạnh", "tránh làm rơi", "đừng làm rơi nhé", "đừng để rơi", "không được rơi", "không được va đập",
        "không được lắc", "đừng lắc", "đừng rung mạnh", "đừng xóc", "đi nhẹ nhàng thôi", "đi nhẹ nhàng giúp", "nhẹ nhàng giúp mình",
        "nhẹ tay thôi nhé", "nhẹ tay giùm", "xin nhẹ tay", "cầm nhẹ nhàng", "nâng niu giúp mình", "giữ cẩn thận giúp", "cẩn thận nhé",
        "cẩn thận giúp mình", "hết sức cẩn thận", "cẩn thận kẻo bể", "cẩn thận kẻo rơi", "coi chừng bể", "coi chừng rơi vỡ",
        "kẻo bể", "kẻo hỏng", "vỡ là mất hết", "bể là hỏng", "hàng nhạy cảm", "thiết bị dễ hỏng", "thiết bị tinh vi dễ hỏng",
        "máy móc nhạy cảm", "linh kiện nhạy cảm", "màn hình dễ vỡ", "kính dễ vỡ", "có kính bên trong", "đồ điện tử dễ hỏng",
        "hàng cần đi êm", "đi êm thôi nhé", "đi thật êm", "chạy êm giúp", "giữ thăng bằng giúp", "đừng nghiêng", "không được nghiêng đổ",
        "giữ thẳng đứng", "hàng dễ đổ", "dễ đổ vỡ", "kỵ va chạm", "kỵ rơi", "sợ va đập", "sợ rơi vỡ", "fragile nhé", "hàng fragile"],
    4: ["không dễ vỡ đâu", "không dễ vỡ nhé", "hàng không dễ vỡ", "đồ không dễ vỡ", "chẳng dễ vỡ", "không vỡ được", "không vỡ đâu",
        "không sợ vỡ", "không lo bể", "không sợ bể", "không dễ hỏng", "không dễ hư", "khó hỏng lắm", "khó bể", "khó vỡ",
        "hàng chắc chắn lắm", "đồ chắc chắn", "rất chắc chắn", "hàng cứng", "đồ cứng cáp", "hàng bền", "đồ bền lắm", "bền lắm",
        "rất bền", "hàng lì đòn", "chịu va đập tốt", "chịu được va đập", "va đập không sao", "va chạm không sao", "rơi không sao",
        "rơi cũng được", "rơi không hỏng", "có rơi cũng không sao", "lỡ rơi cũng chẳng sao", "không sợ rơi vỡ", "không ngại va chạm",
        "không cần nhẹ tay đâu", "không cần nhẹ nhàng", "không cần cẩn thận lắm", "không cần nâng niu đâu", "khỏi cần nhẹ tay",
        "cứ thoải mái mà mang", "mạnh tay cũng được", "xóc cũng không sao", "lắc cũng không sao", "rung lắc thoải mái",
        "toàn giấy tờ thôi", "chỉ là giấy tờ", "toàn sách vở không vỡ", "đồ vải thôi", "toàn quần áo", "đồ nhựa không vỡ",
        "hàng khô", "hàng thường không dễ vỡ", "không phải đồ thủy tinh", "không có thủy tinh", "không có gì dễ hỏng",
        "không có đồ dễ vỡ", "bên trong không có gì dễ vỡ", "đóng gói rất kỹ rồi", "đã bọc chống sốc kỹ", "không mỏng manh gì"],
    0: ["hàng: thùng nước uống", "hàng: tập tài liệu", "hàng: hộp bút", "hàng: bưu kiện", "hàng là một hộp giấy", "món hàng là sách",
        "hàng cần giao là tập hồ sơ", "kiện hàng gồm hai hộp", "đơn gồm một túi đồ", "hàng nặng khoảng hai ký", "hàng nhẹ thôi",
        "hàng to, hơi cồng kềnh", "gói hàng nhỏ", "một thùng nhỏ", "cảm ơn nhé", "cảm ơn nhiều nha", "cảm ơn trước", "cám ơn robot nhiều",
        "thanks nhé", "thank you", "xin cảm ơn", "rất cảm ơn", "nhờ bạn", "nhờ robot nhé", "nhờ robot giúp", "phiền robot", "làm ơn giúp mình",
        "giúp mình với", "giúp mình nhé", "chào bạn", "chào robot nhé", "hello robot", "hi robot", "alo robot", "robot ơi giúp với",
        "có đơn mới", "đơn mới nè", "yêu cầu giao hàng", "yêu cầu mới đây", "thông báo đơn hàng", "nhiệm vụ mới", "nhiệm vụ giao hàng",
        "xác nhận giúp mình", "giao xong báo lại nhé", "tới nơi thì báo", "xong thì nhắn mình", "người nhận sẽ ra lấy", "người nhận tên Lan",
        "gọi người nhận khi tới", "để ở quầy lễ tân", "đặt trước cửa là được", "đưa tận tay người nhận", "nhớ lấy chữ ký", "ký nhận giúp",
        "đã thanh toán rồi", "không thu tiền", "miễn phí giao", "mã đơn ở trên", "số điện thoại ở trên bao bì", "chúc robot làm việc tốt",
        "chúc một ngày vui", "hẹn gặp sau", "vậy thôi nhé", "thế thôi", "hết rồi", "chỉ vậy thôi", "ok nhé", "được rồi đó", "tốt lắm",
        "trời hôm nay đẹp", "hôm nay đông người quá", "đường hơi đông", "nhớ đi đúng đường", "nhớ tuân thủ luật giao thông"],
}

# câu MÔ TẢ từng loại địa điểm (kiến thức chung, không lấy từ test): mô hình nghĩa e5 so một tên gọi lạ với các câu này
# ("không cần học"), bổ sung cho n-gram ký tự / hồi quy trên tên đã biết. Dùng khi nlp2.DESC_W > 0.
TYPE_DESC = {
    "library": ["thư viện, nơi mượn và đọc sách, tài liệu, giáo trình", "nơi tự học yên tĩnh có nhiều sách báo"],
    "dorm": ["ký túc xá, nơi sinh viên ở và ngủ nghỉ", "khu nhà ở nội trú của sinh viên"],
    "sports": ["nơi chơi thể thao, tập luyện thể dục thể thao", "sân bóng, nhà thi đấu, phòng tập gym"],
    "clinic": ["trạm y tế, nơi khám chữa bệnh có bác sĩ, y tá và thuốc", "phòng khám, nơi sơ cứu người bị ốm"],
    "canteen": ["căng tin, nhà ăn, nơi ăn uống và bán đồ ăn thức uống", "bếp ăn tập thể phục vụ bữa ăn"],
    "parking": ["bãi đỗ xe, nơi gửi và giữ xe máy, xe đạp, ô tô", "nhà để xe có người trông xe"],
    "lecture": ["giảng đường, phòng học nơi sinh viên nghe giảng lý thuyết", "lớp học, hội trường để dạy học và thi"],
    "lab": ["phòng thí nghiệm, nơi làm thí nghiệm, thực hành và nghiên cứu khoa học", "xưởng thực hành kỹ thuật, chế tạo"],
    "office": ["văn phòng hành chính, nơi làm thủ tục giấy tờ, hồ sơ, tài chính", "phòng ban quản lý của nhà trường"],
    "gate": ["cổng trường, lối ra vào có bảo vệ trực", "nơi đón tiếp khách đến trường"],
}
# đợt 13 (06/10 chiều): mô tả mở rộng, 8 câu / loại (hoạt động, người làm việc, đồ vật) — kiến thức chung, không lấy từ test.
# Dùng khi nlp2.DESC_MORE = True.
TYPE_DESC2 = {
    "library": ["thư viện trường, nơi mượn, trả và đọc sách, giáo trình, tài liệu tham khảo",
                "phòng đọc yên tĩnh để tự học, ôn bài, tra cứu tài liệu", "kho sách, kho tài liệu, nơi lưu trữ sách báo, luận văn, tạp chí",
                "thủ thư, người quản lý sách và cho mượn sách", "trung tâm học liệu, thông tin tư liệu của trường",
                "nơi đọc báo, xem tạp chí, tìm tài liệu", "quầy mượn trả sách, thẻ thư viện", "góc đọc sách, tủ sách, kệ sách"],
    "dorm": ["ký túc xá, khu nội trú nơi sinh viên ở lại trường", "nhà ở sinh viên, phòng ở tập thể, nơi ngủ nghỉ ban đêm",
             "khu lưu trú cho sinh viên xa nhà, tân sinh viên", "phòng ngủ, giường tầng, chăn gối, đồ giặt",
             "quản lý ký túc xá, bạn cùng phòng, sinh viên nội trú", "dãy nhà ở, tòa nhà ở của sinh viên",
             "nơi sinh viên sinh hoạt, nghỉ ngơi sau giờ học", "chỗ ở, nơi trọ trong khuôn viên trường"],
    "sports": ["nhà thi đấu, sân thể thao, nơi chơi bóng đá, bóng rổ, bóng chuyền, cầu lông",
               "phòng tập gym, thể hình, yoga, võ, nhảy, aerobic", "sân vận động, đường chạy bộ, sân điền kinh", "bể bơi, nơi học bơi",
               "giáo viên thể dục, huấn luyện viên, đội bóng, câu lạc bộ thể thao",
               "nơi tập thể dục, rèn luyện thể chất, giờ học thể chất", "dụng cụ thể thao, quả bóng, vợt, đá cầu",
               "khu vận động, sân tập luyện ngoài trời"],
    "clinic": ["trạm y tế trường, phòng khám chữa bệnh cho sinh viên", "bác sĩ, y tá, điều dưỡng, nhân viên y tế",
               "nơi sơ cứu, cấp cứu khi bị thương, băng bó vết thương", "nơi lấy thuốc, phát thuốc, tiêm phòng, tiêm vắc xin",
               "đo nhiệt độ, huyết áp, kiểm tra sức khỏe, khám tổng quát", "phòng nghỉ cho người ốm, mệt, sốt",
               "phòng y tế, bệnh xá, trạm xá", "tư vấn sức khỏe, chăm sóc y tế"],
    "canteen": ["căng tin, nhà ăn sinh viên, nơi ăn sáng, ăn trưa, ăn tối", "quầy bán cơm, đồ ăn, thức uống, nước giải khát, bánh mì",
                "bếp ăn tập thể, nhà bếp, đầu bếp, người nấu ăn", "khu ẩm thực, quán ăn, quán nước trong trường",
                "suất ăn, khay cơm, phục vụ bữa ăn", "nhân viên bán hàng ăn, cô bán cơm", "phòng ăn chung, bàn ăn",
                "nơi mua đồ ăn vặt, cà phê, trà sữa"],
    "parking": ["bãi xe, nhà xe, nơi gửi và giữ xe máy, xe đạp, ô tô", "người trông xe, bác giữ xe, vé gửi xe",
                "bãi đỗ xe, khu đậu xe, hầm để xe", "chỗ dựng xe, nơi cất xe của sinh viên và nhân viên", "bãi đỗ ô tô cho khách",
                "khu để xe đạp, xe máy điện", "nơi lấy xe, gửi xe", "tầng hầm để xe"],
    "lecture": ["giảng đường, hội trường lớn nơi sinh viên nghe giảng", "phòng học, lớp học lý thuyết, phòng học nhóm",
                "giảng viên, giáo viên, cô giáo chủ nhiệm đang đứng lớp giảng bài", "nơi thi giữa kỳ, cuối kỳ, kiểm tra",
                "tòa nhà học, dãy phòng học, khu giảng dạy", "lớp trưởng, buổi học, tiết học, môn học",
                "phòng chiếu bài giảng, máy chiếu, bảng", "nơi học chuyên đề, seminar, báo cáo"],
    "lab": ["phòng thí nghiệm hóa, lý, sinh, vi sinh", "nơi làm thí nghiệm, pha hóa chất, ống nghiệm, kính hiển vi",
            "xưởng thực hành, xưởng cơ khí, chế tạo, robot", "phòng thực hành máy tính, điện, điện tử",
            "nhóm nghiên cứu, nghiên cứu viên, kỹ thuật viên", "trung tâm nghiên cứu khoa học, viện nghiên cứu",
            "nơi đo đạc, phân tích mẫu, mẫu vật", "phòng lab, phòng thực nghiệm"],
    "office": ["phòng hành chính, văn phòng trường, ban giám hiệu",
               "nơi làm thủ tục, giấy tờ, hồ sơ, đơn từ, giấy xác nhận, giấy giới thiệu",
               "phòng đào tạo, giáo vụ, công tác sinh viên, tuyển sinh, khảo thí", "phòng tài chính, kế toán, tài vụ, nơi nộp học phí",
               "văn thư, thư ký, chuyên viên, cán bộ phòng ban", "nơi đóng dấu, ký duyệt giấy tờ",
               "bộ phận một cửa tiếp nhận hồ sơ sinh viên", "văn phòng khoa, văn phòng đoàn"],
    "gate": ["cổng trường, cổng chính, cổng phụ, lối ra vào", "bảo vệ, chốt gác, phòng trực bảo vệ",
             "nơi đón tiếp khách, người thân đến trường", "lối vào, lối ra, cửa ngõ của trường", "nơi kiểm soát xe và người ra vào",
             "trạm gác, barie, nơi soát vé", "nơi gặp khách bên ngoài", "cổng sau, cổng phía trước"],
}


# đợt 2 (06/10): biến thể chính tả, viết tắt, từ mượn, dạng mô tả, người làm việc — kiến thức chung, không lấy từ test.
# Bỏ các tên mơ hồ giữa hai loại. Gộp vào PLACES_MORE ngay khi nạp mô-đun.
PLACES_MORE2 = {
    "library": ["thư viện số", "thư viện mở", "phòng đọc mở", "phòng mượn sách", "quầy mượn giáo trình", "chỗ mượn giáo trình",
                "nơi mượn giáo trình", "kho lưu trữ tài liệu", "phòng tra cứu", "khu đọc báo", "phòng đọc điện tử", "góc thư viện",
                "trung tâm thông tin tư liệu", "phòng sách tham khảo", "nơi trả giáo trình", "quầy trả giáo trình", "thư quán",
                "phòng tư liệu khoa", "kho sách báo", "nơi đọc báo", "nhân viên quầy mượn sách", "thủ thư trực",
                "cán bộ quản lý sách", "nơi tìm tài liệu", "phòng đọc sinh viên"],
    "dorm": ["kí túc xá", "khu kí túc xá", "nhà trọ sinh viên", "nhà lưu trú", "khu lưu trú sinh viên", "nơi ngủ của sinh viên", "nhà ở tập thể sinh viên", "tòa nhà ký túc",
             "ban tự quản phòng", "cô quản lý khu nội trú", "dãy nhà nội trú", "phòng ở của sinh viên"],
    "sports": ["sân futsal", "sân bóng mini", "sân bóng nhân tạo", "phòng yoga", "phòng aerobic", "phòng múa",
               "câu lạc bộ thể hình", "khu tập gym", "phòng gym trường", "sân bóng chuyền hơi", "sân cầu", "nhà thể dục",
               "khu thể thao đa năng", "sân pickleball", "sân bóng ném", "bể bơi bốn mùa", "đường chạy bộ",
               "sân điền kinh trường", "thầy giáo thể dục", "đội tuyển bóng chuyền", "câu lạc bộ cầu lông", "khu vận động",
               "nơi chơi bóng", "nơi tập thể hình"],
    "clinic": ["phòng y tế học đường", "phòng khám nội", "phòng khám đa khoa trường", "phòng tư vấn sức khỏe", "cơ sở y tế trường",
               "phòng y", "phòng sơ cấp cứu", "trạm sơ cứu", "quầy y tế", "phòng chăm sóc y tế", "khu y tế trường", "nhà thuốc",
               "quầy dược", "phòng khám răng", "bác sĩ trường học", "nhân viên trạm y tế", "chị y tá", "điều dưỡng viên",
               "nơi lấy thuốc", "chỗ khám bệnh"],
    "canteen": ["căn-tin", "cantin", "căng tin sinh viên", "nhà ăn chính", "khu bán đồ ăn", "quầy bánh mì", "quầy cơm trưa",
                "quán ăn trong trường", "khu ăn trưa", "nơi ăn sáng", "bếp ăn trường", "quầy phở", "quầy nước giải khát",
                "quán trà sữa", "căng tin khu", "cô bán căng tin", "anh phục vụ nhà ăn", "nhân viên bán cơm", "nơi bán cơm",
                "chỗ ăn uống"],
    "parking": ["bãi để xe máy", "nhà gửi xe", "khu giữ xe", "chỗ dựng xe", "bãi xe sinh viên", "bãi xe giáo viên",
                "hầm để xe máy", "nhà xe giáo viên", "khu để xe đạp", "bãi gửi xe máy", "điểm gửi xe", "trạm xe đạp",
                "chỗ để ô tô", "bãi đậu ô tô", "người giữ xe", "bác trông xe", "nhân viên bãi xe", "nơi dựng xe",
                "hầm gửi xe máy", "khu đậu xe máy"],
    "lecture": ["phòng học đa năng", "khu giảng dạy", "giảng đường A", "giảng đường B", "phòng học số một", "lớp học lý thuyết",
                "phòng học chung lớn", "phòng học trực tuyến", "phòng thi chung", "phòng chiếu", "hội trường nhỏ",
                "phòng học tầng ba", "khu lớp học chính", "dãy giảng đường", "nhà học A", "tòa nhà giảng đường",
                "giảng viên bộ môn", "thầy chủ nhiệm", "cô chủ nhiệm", "ban cán sự lớp", "nơi dạy học", "chỗ lên lớp"],
    "lab": ["phòng thí nghiệm hóa sinh", "phòng thực tập", "xưởng thực tập kỹ thuật", "phòng mô phỏng", "phòng CAD",
            "phòng thí nghiệm môi trường", "phòng thí nghiệm vật liệu", "phòng thực hành hóa", "phòng thực hành sinh",
            "phòng nghiên cứu robot", "lab AI", "lab trí tuệ nhân tạo", "xưởng điện tử", "xưởng in 3D", "phòng sạch",
            "kỹ thuật viên thí nghiệm", "người trực phòng thí nghiệm", "thầy phụ trách thực hành", "nơi làm thực hành",
            "chỗ làm thí nghiệm"],
    "office": ["phòng CTSV", "phòng công tác chính trị", "phòng quản lý sinh viên", "phòng đào tạo đại học",
               "phòng khảo thí và đảm bảo chất lượng", "văn phòng đoàn", "đoàn trường", "hội sinh viên", "văn phòng hội sinh viên",
               "phòng tổ chức cán bộ", "phòng kế hoạch", "phòng truyền thông", "phòng thu học phí", "quầy thu ngân",
               "phòng tài chính kế toán", "chuyên viên phòng đào tạo", "cô thư ký khoa", "chị văn phòng khoa",
               "thầy hiệu trưởng", "cô hiệu phó", "nơi đóng học phí", "chỗ làm giấy tờ",
               "khu hiệu bộ", "khu điều hành", "thư ký trường", "thư ký văn phòng"],
    "gate": ["cổng số 1", "cổng số 2", "cổng phụ phía sau", "cổng chính của trường", "cổng ra vào chính", "lối vào phụ",
             "cửa ra vào chính", "chòi bảo vệ", "trạm kiểm soát", "chốt kiểm soát ra vào", "barie", "quầy đón tiếp",
             "khu tiếp khách ở cổng", "nhân viên bảo vệ cổng", "chú bảo vệ cổng", "anh lễ tân", "đội bảo vệ trường",
             "nơi khách chờ", "chỗ đón khách"],
}

# đợt 17 (07/10): tên kiểu MÔ TẢ CHỨC NĂNG ("nơi / chỗ / góc / phòng + việc làm ở đó") và cách gọi đời thường — kiến thức
# chung, viết mới (không lấy từ test, đã bỏ mọi tên trùng bộ thử scratch/h31 để phép thử h31 / h48 vẫn là đo độc lập).
PLACES_MORE3 = {
    "library": ["chỗ đọc sách yên tĩnh", "chỗ tìm sách", "góc sách tham khảo", "phòng đọc báo chí", "nơi học nhóm im lặng", "phòng mượn trả sách", "quầy thủ thư", "nơi gửi trả sách", "khu tự học yên tĩnh", "phòng tài liệu điện tử", "nơi đọc luận văn", "kho luận văn", "phòng đọc tự chọn", "tủ sách chung", "nơi in tài liệu thư viện", "phòng đọc sách báo"],
    "dorm": ["khu ở nội trú", "nhà ở học viên", "khu tập thể sinh viên", "dãy phòng ngủ", "khu phòng trọ trong trường", "chỗ ở tập thể", "căn hộ sinh viên", "khu ở của học viên", "dãy phòng nội trú nam", "dãy phòng nội trú nữ"],
    "sports": ["chỗ chơi bóng", "khu chơi thể thao", "nơi tập võ", "sân quần vợt", "sân tennis", "chỗ tập chạy", "khu rèn luyện thể chất", "nơi học thể dục", "phòng bóng bàn", "nơi chơi cầu lông", "hồ bơi trường", "nơi thi đấu thể thao"],
    "clinic": ["nơi khám sức khỏe", "chỗ sơ cứu", "nơi phát thuốc", "phòng khám sức khỏe", "nơi tiêm chủng", "phòng nghỉ bệnh", "giường bệnh", "phòng bác sĩ", "phòng y sĩ", "phòng khám mắt", "nơi tư vấn sức khỏe", "phòng hồi sức", "chỗ nằm nghỉ khi ốm", "quầy phát thuốc"],
    "canteen": ["nơi ăn cơm", "quầy đồ ăn", "nơi mua đồ ăn", "quầy cà phê", "quán cà phê trường", "chỗ uống nước", "quầy giải khát", "nơi bán đồ uống", "khu ăn uống", "nhà ăn tập thể", "quầy bán bánh", "bếp ăn tập thể", "quầy suất ăn", "khu food court", "quầy ăn vặt", "nơi phục vụ bữa trưa"],
    "parking": ["chỗ gửi xe máy", "chỗ đỗ ô tô", "bến đỗ xe", "nơi trông xe", "khu xe điện", "trạm sạc xe điện", "chỗ đỗ xe giáo viên", "bãi xe khách", "nơi đỗ xe buýt", "điểm đỗ xe"],
    "lecture": ["chỗ học lý thuyết", "phòng học chuyên đề", "phòng seminar", "phòng hội thảo", "nơi thi học kỳ", "phòng học tiếng anh", "phòng học ngoại ngữ", "khu nhà học", "tòa học", "phòng học máy chiếu", "nơi học tập trung", "phòng học trên tầng"],
    "lab": ["chỗ thực hành", "phòng thực nghiệm", "nơi phân tích mẫu", "phòng thực hành điện", "xưởng thực hành", "phòng đo lường", "phòng kiểm nghiệm", "nơi pha chế hóa chất", "phòng nuôi cấy", "phòng thực hành vật lý", "phòng thử nghiệm"],
    "office": ["chỗ nộp hồ sơ", "bộ phận một cửa", "phòng văn thư", "phòng tiếp nhận hồ sơ", "phòng tuyển sinh", "phòng hợp tác quốc tế", "phòng thanh tra", "phòng hiệu trưởng", "nơi đăng ký học phần", "phòng hỗ trợ người học", "trung tâm hỗ trợ sinh viên"],
    "gate": ["cổng vào", "cổng bên hông", "cổng hông", "chốt bảo vệ", "nơi bảo vệ trực", "cổng đón khách", "cổng lớn", "cổng nhỏ", "nơi kiểm tra ra vào"],
}

import os as _os
for _t, _v in (PLACES_MORE3.items() if _os.environ.get("NO_MORE3") != "1" else []):
    PLACES_MORE2[_t] = PLACES_MORE2[_t] + [x for x in _v if x not in PLACES_MORE2[_t]]
for _t, _v in (PLACES_MORE2.items() if _os.environ.get("NO_MORE2") != "1" else []):
    PLACES_MORE[_t] = PLACES_MORE[_t] + [x for x in _v if x not in PLACES_MORE[_t] and x not in PLACES[_t]]
