"""Kiến thức tiếng Việt viết tay để mô hình nghĩa (e5) có thêm ví dụ về những cách nói CHƯA có trong train/validation.

Tất cả được viết từ hiểu biết ngôn ngữ chung, KHÔNG lấy từ nội dung test.
"""

# 0 trung tính, 1 gấp, 2 dễ vỡ, 3 không gấp, 4 không dễ vỡ
PHRASES = {
    1: ["gấp lắm", "việc gấp", "khẩn cấp", "rất khẩn", "cần ngay", "giao ngay lập tức", "đi ngay nhé", "làm ngay đi",
        "càng sớm càng tốt", "càng nhanh càng tốt", "đừng chậm trễ", "không được chậm trễ", "không được trễ", "ưu tiên hàng đầu",
        "ưu tiên số một", "ưu tiên cao nhất", "hỏa tốc", "đơn hỏa tốc", "nhanh lên nhé", "nhanh nhất có thể", "khẩn trương lên",
        "khẩn trương giúp mình", "cấp tốc", "tức tốc", "sắp trễ rồi", "kẻo trễ", "kẻo muộn", "người nhận đang chờ gấp",
        "đang rất cần", "đang cần gấp", "phải tới trong vài phút nữa", "cần trong năm phút", "trong vòng mười phút", "giao liền nhé",
        "không thể chậm hơn", "thời gian rất gấp", "đang vội lắm", "rất vội", "chạy nhanh giúp mình", "việc này không chờ được",
        "hạn chót sắp đến", "cần kíp", "lẹ lên nhé", "đi lẹ giúp", "phải kịp trước giờ", "đừng để lâu", "không được để chờ lâu",
        "ưu tiên đơn này trước", "xử lý ngay", "giao hỏa tốc", "gấp gáp lắm", "cần gấp trong hôm nay ngay bây giờ",
        "không thể chờ thêm", "đừng để người nhận chờ", "chậm là không kịp", "không nhanh là trễ", "phải có mặt ngay",
        "việc này rất gấp", "đơn khẩn", "đơn gấp", "người ta đang hối", "bên kia đang giục", "cần liền", "nhanh nhanh giúp",
        "thời gian không còn nhiều", "sát giờ rồi", "đang chờ từng phút", "càng lẹ càng tốt", "đi liền nha"],
    3: ["không gấp", "không gấp đâu", "không vội", "không cần vội", "cứ từ từ", "cứ thong thả", "thong thả thôi", "lúc nào giao cũng được",
        "khi nào giao cũng được", "mai giao cũng được", "mai giao cũng kịp", "chiều nay giao cũng được", "khi nào rảnh thì giao",
        "tiện lúc nào thì giao", "không cần nhanh", "chậm một chút cũng được", "không có gì gấp", "không cần ưu tiên", "bao giờ tới cũng được",
        "đi thong thả", "không phải vội", "chưa cần ngay", "để sau cũng được", "thời gian thoải mái", "không hạn chót", "từ từ mà đi",
        "khỏi cần vội", "không việc gì phải gấp", "trễ một chút không sao", "muộn cũng không sao", "tối giao cũng kịp", "tuần sau cũng được",
        "chẳng có gì phải vội", "gấp gì đâu", "đâu cần nhanh", "khỏi phải khẩn trương", "chưa cần gấp", "không cần phải ngay",
        "chẳng gấp gáp gì", "thư thả mà đi", "không ai hối đâu", "đơn thường thôi", "không ưu tiên gì", "cứ bình tĩnh",
        "nhàn nhã thôi", "lúc nào tiện thì đi", "không cần khẩn trương", "đâu có gấp", "vội gì đâu", "còn nhiều thời gian"],
    2: ["hàng dễ vỡ", "đồ dễ vỡ", "dễ vỡ lắm", "bên trong là đồ thủy tinh", "đồ thủy tinh", "đồ gốm sứ", "đồ gốm bên trong", "đồ sứ",
        "nhẹ tay giúp", "nhẹ tay nhé", "xin nhẹ nhàng", "cẩn thận kẻo vỡ", "đi cẩn thận", "hàng mỏng manh", "kiện hàng mỏng manh",
        "tránh va đập", "tránh va chạm", "kỵ va đập", "kỵ rung lắc", "tránh rung lắc", "dễ hỏng khi va đập", "dễ hỏng", "đừng làm rơi",
        "không được làm rơi", "hàng cần nâng niu", "dễ nứt", "dễ bể", "dễ móp", "đồ pha lê", "bên trong có chai lọ", "thiết bị nhạy cảm",
        "linh kiện dễ hỏng", "không được va chạm mạnh", "cầm cẩn thận", "hàng cần nhẹ tay", "chú ý hàng dễ vỡ", "xin đừng lắc mạnh",
        "đồ rất dễ vỡ", "có đồ thủy tinh bên trong", "hàng dễ bị vỡ", "hàng yếu, đi êm thôi", "đi êm giúp mình", "giữ thăng bằng kẻo đổ vỡ",
        "màn hình dễ nứt", "đồ điện tử nhạy cảm", "không chịu được va đập", "không được quăng ném", "đừng xóc mạnh",
        "hàng dễ vỡ xin nhẹ tay", "coi chừng vỡ", "kẻo vỡ", "vỡ là hỏng hết", "đồ dễ gãy", "hàng dễ dập", "chứa đồ thủy tinh",
        "đồ sành sứ", "ly tách bên trong", "bóng đèn bên trong", "hàng nhạy cảm với va chạm", "xin giữ nhẹ nhàng", "nâng như nâng trứng"],
    4: ["không dễ vỡ", "hàng chắc chắn", "hàng chắc chắn, không dễ vỡ", "rơi cũng không sao", "rơi cũng chẳng sao", "đồ bền",
        "hàng bền, không lo vỡ", "không sợ va đập", "không lo vỡ", "đồ không vỡ được", "hàng cứng cáp", "không cần nhẹ tay",
        "va đập thoải mái", "không sợ rơi", "chắc lắm không vỡ đâu", "đồ nhựa cứng không vỡ", "không có gì dễ vỡ", "hàng không dễ hỏng",
        "khó vỡ lắm", "không mỏng manh", "cứ mạnh tay", "không cần cẩn thận quá", "đồ vải không sợ rơi", "hàng không kỵ va đập",
        "vỡ sao được", "chẳng dễ vỡ đâu", "không phải hàng dễ vỡ", "rơi vỡ gì đâu", "không cần nâng niu", "đâu có dễ vỡ",
        "đồ này lì lắm", "quăng cũng không sao", "va chạm cũng chẳng hề gì", "không sợ móp", "hàng khô không vỡ", "toàn giấy tờ không vỡ được"],
    0: ["cảm ơn", "cảm ơn nhiều", "cảm ơn bạn", "cảm ơn robot", "thanks robot", "xin chào", "chào robot", "robot ơi", "nhờ bạn nhé",
        "yêu cầu mới", "nhắn robot", "chúc một ngày tốt lành", "hẹn gặp lại", "phiền bạn nhé", "nhờ cả vào bạn", "làm tốt lắm",
        "đơn mới đây", "có việc nhờ đây", "xin nhờ một việc", "vậy nhé", "thế nhé", "trân trọng"],
}

# cách gọi khác của từng loại địa điểm
PLACES = {
    "library": ["thư viện", "thư viện trường", "phòng đọc", "khu đọc sách", "nơi mượn sách", "chỗ trả sách", "kho sách", "phòng sách",
                "trung tâm học liệu", "phòng tư liệu", "phòng tài liệu", "nơi tra cứu tài liệu", "quầy mượn trả sách", "tủ sách chung",
                "phòng báo chí", "nơi đọc sách", "thủ thư", "cán bộ thư viện", "quầy thủ thư"],
    "dorm": ["ký túc xá", "ktx", "khu ký túc", "khu nội trú", "nhà ở sinh viên", "khu ở của sinh viên", "phòng ở sinh viên", "khu lưu trú",
             "cư xá sinh viên", "dãy phòng nội trú", "nơi sinh viên ở", "làng sinh viên", "khu nhà ở", "phòng ngủ sinh viên", "khu phòng trọ sinh viên",
             "nhà nghỉ sinh viên", "ban quản lý ký túc xá", "sinh viên nội trú", "quản lý ký túc"],
    "sports": ["nhà thể thao", "nhà thi đấu", "khu thể thao", "sân thể thao", "sân bóng", "sân tập", "nhà thể chất", "phòng tập", "phòng gym",
               "khu vận động", "sân luyện tập", "nhà đa năng", "sân vận động", "sân cầu lông", "sân bóng rổ", "bể bơi", "khu thể dục",
               "nơi tập thể dục", "huấn luyện viên", "đội bóng", "câu lạc bộ thể thao", "sân chơi thể thao"],
    "clinic": ["trạm y tế", "phòng y tế", "trạm xá", "phòng khám", "phòng khám của trường", "phòng sơ cứu", "khu y tế", "nơi khám sức khỏe",
               "phòng bác sĩ", "bệnh xá", "phòng cấp cứu", "phòng điều dưỡng", "phòng thuốc", "quầy thuốc", "nơi chăm sóc sức khỏe",
               "bác sĩ trường", "y tá trực", "nhân viên y tế", "phòng khám bệnh"],
    "canteen": ["căn tin", "căng tin", "canteen", "nhà ăn", "bếp ăn", "khu ăn uống", "phòng ăn", "phòng ăn tập thể", "quán ăn sinh viên",
                "khu ẩm thực", "nơi phục vụ bữa trưa", "quầy ăn", "nhà bếp", "quầy đồ ăn", "nơi ăn trưa", "quán cà phê trong trường",
                "bếp trưởng", "cô cấp dưỡng", "nhân viên quầy ăn", "quầy giải khát"],
    "parking": ["bãi xe", "bãi đỗ xe", "bãi gửi xe", "nhà xe", "hầm xe", "khu gửi xe", "chỗ để xe", "nơi giữ xe", "khu đậu xe", "bãi đậu xe",
                "bãi giữ xe", "nhà để xe", "ga ra", "bãi xe máy", "bãi ô tô", "điểm trông xe", "bác giữ xe", "nhân viên trông xe", "chỗ gửi xe đạp"],
    "lecture": ["giảng đường", "tòa giảng đường", "khu giảng đường", "phòng học", "phòng học lớn", "lớp học", "hội trường học", "dãy phòng học",
                "nơi lên lớp", "nhà học", "tòa nhà học", "khu lớp học", "phòng giảng", "hội trường", "nơi nghe giảng", "giảng viên đang dạy",
                "lớp trưởng", "cán sự lớp", "phòng học lý thuyết"],
    "lab": ["phòng thí nghiệm", "phòng lab", "lab hóa", "khu thí nghiệm", "phòng thực hành", "xưởng thực hành", "phòng thực nghiệm",
            "nơi làm thí nghiệm", "phòng nghiên cứu", "trung tâm thí nghiệm", "xưởng thực tập", "phòng máy thực hành", "phòng lab sinh học",
            "kỹ thuật viên phòng lab", "nhóm nghiên cứu", "người hướng dẫn thực hành", "phòng thí nghiệm vật lý"],
    "office": ["phòng hành chính", "khu hành chính", "văn phòng khoa", "phòng đào tạo", "phòng một cửa", "tòa hiệu bộ", "phòng giáo vụ",
               "nơi nộp hồ sơ", "văn phòng", "phòng công tác sinh viên", "phòng tài vụ", "phòng kế toán", "phòng tổ chức", "văn thư",
               "ban giám hiệu", "phòng tuyển sinh", "phòng khảo thí", "nơi làm thủ tục", "thư ký khoa", "chuyên viên một cửa", "cán bộ phòng đào tạo"],
    "gate": ["cổng trường", "cổng chính", "cổng vào", "cổng a", "lối vào trường", "chốt bảo vệ cổng", "chốt cổng", "nơi khách đến trường",
             "cổng phụ", "cổng sau", "cửa vào trường", "trạm gác", "phòng bảo vệ", "chốt gác", "lối ra vào", "nơi đón khách", "bảo vệ cổng",
             "tổ đón khách", "nhân viên trực cổng", "quầy lễ tân cổng"],
}
