"""Kiến thức tiếng Việt viết tay để mô hình nghĩa (e5) có thêm ví dụ về những cách nói CHƯA có trong train/validation.

Tất cả được viết từ hiểu biết ngôn ngữ chung, KHÔNG lấy từ nội dung test.
"""

# 0 trung tính, 1 gấp, 2 dễ vỡ, 3 không gấp, 4 không dễ vỡ
PHRASES = {
    1: ["gấp lắm", "việc gấp", "khẩn cấp", "rất khẩn", "cần ngay", "giao ngay lập tức", "đi ngay nhé", "làm ngay đi",
        "càng sớm càng tốt", "càng nhanh càng tốt", "đừng chậm trễ", "không được chậm trễ", "không được trễ", "ưu tiên hàng đầu",
        "ưu tiên số một", "ưu tiên cao nhất", "hỏa tốc", "đơn hỏa tốc", "nhanh lên nhé", "nhanh nhất có thể", "khẩn trương lên",
        "khẩn trương giúp mình", "cấp tốc", "tức tốc", "sắp trễ rồi", "kẻo trễ", "kẻo muộn", "người nhận đang chờ gấp",
        "đang rất cần", "đang cần gấp", "phải tới trong vài phút nữa", "cần trong năm phút", "trong vòng mười phút", "giao liền nhé",
        "không thể chậm hơn", "thời gian rất gấp", "đang vội lắm", "rất vội", "chạy nhanh giúp mình", "việc này không chờ được",
        "hạn chót sắp đến", "cần kíp", "lẹ lên nhé", "đi lẹ giúp", "phải kịp trước giờ", "đừng để lâu", "không được để chờ lâu",
        "ưu tiên đơn này trước", "xử lý ngay", "giao hỏa tốc", "gấp gáp lắm", "cần gấp trong hôm nay ngay bây giờ",
        "không thể chờ thêm", "đừng để người nhận chờ", "chậm là không kịp", "không nhanh là trễ", "phải có mặt ngay",
        "việc này rất gấp", "đơn khẩn", "đơn gấp", "người ta đang hối", "bên kia đang giục", "cần liền", "nhanh nhanh giúp",
        "thời gian không còn nhiều", "sát giờ rồi", "đang chờ từng phút", "càng lẹ càng tốt", "đi liền nha",
        # (bổ sung 2026-10-03: thêm các kiểu nói gấp theo hạn giờ, thúc giục, tốc độ)
        "phải xong trước 9 giờ", "trước 10 giờ phải có", "hạn chót là 15 phút nữa", "còn 5 phút nữa thôi", "chỉ còn ít phút",
        "sắp đến giờ rồi", "sắp vào lớp rồi", "sắp bắt đầu rồi", "buổi họp sắp bắt đầu", "sắp hết giờ", "sắp hết hạn",
        "deadline tới nơi rồi", "đang chạy deadline", "trễ giờ mất", "muộn giờ mất rồi", "cho kịp giờ", "phải kịp giờ học",
        "người nhận đang đợi sẵn", "bên nhận đang đứng chờ", "đang ngóng từng giây", "đang sốt ruột chờ", "đang nóng ruột lắm",
        "bị giục nãy giờ", "sếp đang hối", "thầy đang chờ gấp", "bệnh nhân đang chờ", "ca cấp cứu đang chờ",
        "nước sôi lửa bỏng", "cháy tới nơi rồi", "chuyện gấp như cứu hỏa", "tình huống khẩn", "trường hợp khẩn cấp",
        "giao tốc hành", "giao siêu tốc", "giao thần tốc", "đi hết tốc lực", "chạy hết tốc lực", "phóng nhanh giúp",
        "đi đường nhanh nhất", "chọn đường ngắn nhất cho nhanh", "đừng la cà", "đừng dừng dọc đường", "đi thẳng một mạch",
        "tranh thủ giúp mình", "tranh thủ từng phút", "ngay tức khắc", "tức khắc", "cấp kỳ", "liền tay giúp", "làm liền",
        "ASAP nhé", "express nhé", "không được phép chậm", "chậm một phút cũng không được", "một giây cũng quý",
        "không có thời gian đâu", "hết thời gian rồi", "thời gian là vàng lúc này", "mau lên", "mau mau giúp", "lẹ lẹ giùm",
        "nhanh chân lên", "khẩn thiết", "bức thiết lắm", "cần gấp gáp", "đơn ưu tiên", "ưu tiên xử lý trước"],
    3: ["không gấp", "không gấp đâu", "không vội", "không cần vội", "cứ từ từ", "cứ thong thả", "thong thả thôi", "lúc nào giao cũng được",
        "khi nào giao cũng được", "mai giao cũng được", "mai giao cũng kịp", "chiều nay giao cũng được", "khi nào rảnh thì giao",
        "tiện lúc nào thì giao", "không cần nhanh", "chậm một chút cũng được", "không có gì gấp", "không cần ưu tiên", "bao giờ tới cũng được",
        "đi thong thả", "không phải vội", "chưa cần ngay", "để sau cũng được", "thời gian thoải mái", "không hạn chót", "từ từ mà đi",
        "khỏi cần vội", "không việc gì phải gấp", "trễ một chút không sao", "muộn cũng không sao", "tối giao cũng kịp", "tuần sau cũng được",
        "chẳng có gì phải vội", "gấp gì đâu", "đâu cần nhanh", "khỏi phải khẩn trương", "chưa cần gấp", "không cần phải ngay",
        "chẳng gấp gáp gì", "thư thả mà đi", "không ai hối đâu", "đơn thường thôi", "không ưu tiên gì", "cứ bình tĩnh",
        "nhàn nhã thôi", "lúc nào tiện thì đi", "không cần khẩn trương", "đâu có gấp", "vội gì đâu", "còn nhiều thời gian",
        "trong ngày là được", "trong tuần là được", "cuối ngày giao cũng ổn", "hôm nào giao cũng được", "không giới hạn thời gian",
        "không có deadline", "hạn còn xa", "còn dư dả thời gian", "không ai chờ đâu", "người nhận không vội", "đi chậm cũng được",
        "không cần chạy nhanh", "cứ đi bình thường", "tốc độ bình thường là được", "đơn không ưu tiên", "xếp sau các đơn khác cũng được",
        "rảnh thì làm", "tiện đường thì ghé", "ung dung mà đi", "thoải mái thời gian", "không phải hỏa tốc", "không khẩn cấp",
        "chẳng cần hối", "đâu ai giục", "trễ chút cũng chẳng sao", "tối nay hay mai đều được"],
    2: ["hàng dễ vỡ", "đồ dễ vỡ", "dễ vỡ lắm", "bên trong là đồ thủy tinh", "đồ thủy tinh", "đồ gốm sứ", "đồ gốm bên trong", "đồ sứ",
        "nhẹ tay giúp", "nhẹ tay nhé", "xin nhẹ nhàng", "cẩn thận kẻo vỡ", "đi cẩn thận", "hàng mỏng manh", "kiện hàng mỏng manh",
        "tránh va đập", "tránh va chạm", "kỵ va đập", "kỵ rung lắc", "tránh rung lắc", "dễ hỏng khi va đập", "dễ hỏng", "đừng làm rơi",
        "không được làm rơi", "hàng cần nâng niu", "dễ nứt", "dễ bể", "dễ móp", "đồ pha lê", "bên trong có chai lọ", "thiết bị nhạy cảm",
        "linh kiện dễ hỏng", "không được va chạm mạnh", "cầm cẩn thận", "hàng cần nhẹ tay", "chú ý hàng dễ vỡ", "xin đừng lắc mạnh",
        "đồ rất dễ vỡ", "có đồ thủy tinh bên trong", "hàng dễ bị vỡ", "hàng yếu, đi êm thôi", "đi êm giúp mình", "giữ thăng bằng kẻo đổ vỡ",
        "màn hình dễ nứt", "đồ điện tử nhạy cảm", "không chịu được va đập", "không được quăng ném", "đừng xóc mạnh",
        "hàng dễ vỡ xin nhẹ tay", "coi chừng vỡ", "kẻo vỡ", "vỡ là hỏng hết", "đồ dễ gãy", "hàng dễ dập", "chứa đồ thủy tinh",
        "đồ sành sứ", "ly tách bên trong", "bóng đèn bên trong", "hàng nhạy cảm với va chạm", "xin giữ nhẹ nhàng", "nâng như nâng trứng"],
    4: ["không dễ vỡ", "hàng chắc chắn", "hàng chắc chắn, không dễ vỡ", "rơi cũng không sao", "rơi cũng chẳng sao", "đồ bền",
        "hàng bền, không lo vỡ", "không sợ va đập", "không lo vỡ", "đồ không vỡ được", "hàng cứng cáp", "không cần nhẹ tay",
        "va đập thoải mái", "không sợ rơi", "chắc lắm không vỡ đâu", "đồ nhựa cứng không vỡ", "không có gì dễ vỡ", "hàng không dễ hỏng",
        "khó vỡ lắm", "không mỏng manh", "cứ mạnh tay", "không cần cẩn thận quá", "đồ vải không sợ rơi", "hàng không kỵ va đập",
        "vỡ sao được", "chẳng dễ vỡ đâu", "không phải hàng dễ vỡ", "rơi vỡ gì đâu", "không cần nâng niu", "đâu có dễ vỡ",
        "đồ này lì lắm", "quăng cũng không sao", "va chạm cũng chẳng hề gì", "không sợ móp", "hàng khô không vỡ", "toàn giấy tờ không vỡ được"],
    0: ["cảm ơn", "cảm ơn nhiều", "cảm ơn bạn", "cảm ơn robot", "thanks robot", "xin chào", "chào robot", "robot ơi", "nhờ bạn nhé",
        "yêu cầu mới", "nhắn robot", "chúc một ngày tốt lành", "hẹn gặp lại", "phiền bạn nhé", "nhờ cả vào bạn", "làm tốt lắm",
        "đơn mới đây", "có việc nhờ đây", "xin nhờ một việc", "vậy nhé", "thế nhé", "trân trọng"],
}

# cách gọi khác của từng loại địa điểm
PLACES = {
    "library": ["thư viện", "thư viện trường", "phòng đọc", "khu đọc sách", "nơi mượn sách", "chỗ trả sách", "kho sách", "phòng sách",
                "trung tâm học liệu", "phòng tư liệu", "phòng tài liệu", "nơi tra cứu tài liệu", "quầy mượn trả sách", "tủ sách chung",
                "phòng báo chí", "nơi đọc sách", "thủ thư", "cán bộ thư viện", "quầy thủ thư"],
    "dorm": ["ký túc xá", "ktx", "khu ký túc", "khu nội trú", "nhà ở sinh viên", "khu ở của sinh viên", "phòng ở sinh viên", "khu lưu trú",
             "cư xá sinh viên", "dãy phòng nội trú", "nơi sinh viên ở", "làng sinh viên", "khu nhà ở", "phòng ngủ sinh viên", "khu phòng trọ sinh viên",
             "nhà nghỉ sinh viên", "ban quản lý ký túc xá", "sinh viên nội trú", "quản lý ký túc"],
    "sports": ["nhà thể thao", "nhà thi đấu", "khu thể thao", "sân thể thao", "sân bóng", "sân tập", "nhà thể chất", "phòng tập", "phòng gym",
               "khu vận động", "sân luyện tập", "nhà đa năng", "sân vận động", "sân cầu lông", "sân bóng rổ", "bể bơi", "khu thể dục",
               "nơi tập thể dục", "huấn luyện viên", "đội bóng", "câu lạc bộ thể thao", "sân chơi thể thao"],
    "clinic": ["trạm y tế", "phòng y tế", "trạm xá", "phòng khám", "phòng khám của trường", "phòng sơ cứu", "khu y tế", "nơi khám sức khỏe",
               "phòng bác sĩ", "bệnh xá", "phòng cấp cứu", "phòng điều dưỡng", "phòng thuốc", "quầy thuốc", "nơi chăm sóc sức khỏe",
               "bác sĩ trường", "y tá trực", "nhân viên y tế", "phòng khám bệnh"],
    "canteen": ["căn tin", "căng tin", "canteen", "nhà ăn", "bếp ăn", "khu ăn uống", "phòng ăn", "phòng ăn tập thể", "quán ăn sinh viên",
                "khu ẩm thực", "nơi phục vụ bữa trưa", "quầy ăn", "nhà bếp", "quầy đồ ăn", "nơi ăn trưa", "quán cà phê trong trường",
                "bếp trưởng", "cô cấp dưỡng", "nhân viên quầy ăn", "quầy giải khát"],
    "parking": ["bãi xe", "bãi đỗ xe", "bãi gửi xe", "nhà xe", "hầm xe", "khu gửi xe", "chỗ để xe", "nơi giữ xe", "khu đậu xe", "bãi đậu xe",
                "bãi giữ xe", "nhà để xe", "ga ra", "bãi xe máy", "bãi ô tô", "điểm trông xe", "bác giữ xe", "nhân viên trông xe", "chỗ gửi xe đạp"],
    "lecture": ["giảng đường", "tòa giảng đường", "khu giảng đường", "phòng học", "phòng học lớn", "lớp học", "hội trường học", "dãy phòng học",
                "nơi lên lớp", "nhà học", "tòa nhà học", "khu lớp học", "phòng giảng", "hội trường", "nơi nghe giảng", "giảng viên đang dạy",
                "lớp trưởng", "cán sự lớp", "phòng học lý thuyết"],
    "lab": ["phòng thí nghiệm", "phòng lab", "lab hóa", "khu thí nghiệm", "phòng thực hành", "xưởng thực hành", "phòng thực nghiệm",
            "nơi làm thí nghiệm", "phòng nghiên cứu", "trung tâm thí nghiệm", "xưởng thực tập", "phòng máy thực hành", "phòng lab sinh học",
            "kỹ thuật viên phòng lab", "nhóm nghiên cứu", "người hướng dẫn thực hành", "phòng thí nghiệm vật lý"],
    "office": ["phòng hành chính", "khu hành chính", "văn phòng khoa", "phòng đào tạo", "phòng một cửa", "tòa hiệu bộ", "phòng giáo vụ",
               "nơi nộp hồ sơ", "văn phòng", "phòng công tác sinh viên", "phòng tài vụ", "phòng kế toán", "phòng tổ chức", "văn thư",
               "ban giám hiệu", "phòng tuyển sinh", "phòng khảo thí", "nơi làm thủ tục", "thư ký khoa", "chuyên viên một cửa", "cán bộ phòng đào tạo"],
    "gate": ["cổng trường", "cổng chính", "cổng vào", "cổng a", "lối vào trường", "chốt bảo vệ cổng", "chốt cổng", "nơi khách đến trường",
             "cổng phụ", "cổng sau", "cửa vào trường", "trạm gác", "phòng bảo vệ", "chốt gác", "lối ra vào", "nơi đón khách", "bảo vệ cổng",
             "tổ đón khách", "nhân viên trực cổng", "quầy lễ tân cổng"],
}

# ---- Bổ sung 2026-10-04: thêm nhiều cách nói cho cả 5 lớp (kiến thức tiếng Việt chung, KHÔNG lấy từ test) ----
# Mục đích: mô hình nghĩa phân biệt được "gấp" với "không gấp / thong thả" và với câu trung tính ở những cách nói chưa gặp.
PHRASES_MORE = {
    1: ["giao gấp giúp mình", "mình cần gấp", "em cần gấp lắm ạ", "gấp quá rồi", "rất gấp", "cực kỳ gấp", "gấp lắm rồi đó",
        "việc này gấp", "đơn này gấp", "chuyện gấp", "cần gấp trong buổi sáng", "gấp không chờ được", "cần ngay bây giờ",
        "cần ngay lập tức", "giao ngay giúp", "đi ngay giúp mình", "xuất phát ngay", "lên đường ngay", "làm ngay giúp",
        "ngay và luôn", "ngay tức thì", "lập tức lên đường", "khẩn cấp lắm", "khẩn lắm", "rất khẩn cấp", "việc khẩn",
        "tình hình khẩn cấp", "khẩn trương nhé", "khẩn trương lên nào", "nhanh lên giúp mình", "nhanh nhất có thể nhé",
        "càng sớm càng tốt nhé", "sớm nhất có thể", "trong thời gian sớm nhất", "thật nhanh giúp mình", "nhanh hết mức",
        "đừng chậm trễ nhé", "không được chậm", "không được muộn", "không được đến trễ", "chậm là hỏng việc",
        "trễ là hỏng hết", "muộn là không kịp", "không kịp mất", "sợ không kịp", "phải kịp trước buổi học", "kịp giờ họp nhé",
        "còn mười phút nữa là vào học", "còn ít phút nữa thôi", "chỉ còn vài phút", "trong vòng năm phút", "trong ít phút tới",
        "năm phút nữa phải có", "mười phút nữa cần dùng", "sắp tới giờ rồi", "sắp vào tiết", "sắp họp rồi", "sắp thi rồi",
        "người nhận đang cần gấp", "người nhận đang đợi", "bên kia đang đợi", "đang đợi ngoài cửa", "đang chờ sẵn ở đó",
        "đang ngóng lắm", "đang sốt ruột lắm", "nóng ruột chờ", "bị hối suốt", "sếp giục rồi", "thầy đang giục",
        "ưu tiên cao", "ưu tiên gấp", "ưu tiên trước hết", "ưu tiên hàng đầu nhé", "làm trước các đơn khác", "đẩy đơn này lên trước",
        "hỏa tốc nhé", "giao hỏa tốc giúp", "chuyển phát hỏa tốc", "giao nhanh giúp mình", "giao lẹ giúp", "lẹ lên", "mau lên nhé",
        "đi mau giúp", "chạy nhanh lên", "tăng tốc lên", "hết sức khẩn trương", "không có thời gian chờ", "không chờ lâu được",
        "không thể đợi", "đợi lâu không được", "thời gian gấp rút", "gấp rút lắm", "cấp bách", "việc cấp bách", "rất cấp thiết",
        "cần kíp lắm", "nước đến chân rồi", "sát nút rồi", "trễ lắm rồi", "muộn lắm rồi", "đã trễ rồi nhanh lên",
        "time gấp", "urgent nhé", "cần urgent", "đơn urgent", "giao liền giúp", "giao luôn và ngay", "cần liền bây giờ"],
    3: ["không gấp nhé", "không gấp gì", "không gấp lắm", "chưa gấp", "chưa gấp đâu", "chẳng gấp", "chả gấp gì", "đâu có gì gấp",
        "không vội đâu", "không vội gì", "chưa vội", "đừng vội", "đừng vội vàng", "đừng gấp", "khỏi vội", "không phải gấp đâu",
        "cứ từ từ nhé", "cứ từ từ mà làm", "từ từ thôi", "từ từ cũng được", "thong thả nhé", "cứ thong thả mà đi", "thư thả thôi",
        "thoải mái đi", "cứ thoải mái", "thoải mái thời gian nhé", "lúc nào cũng được", "khi nào cũng được", "bao giờ cũng được",
        "hôm nay hay mai đều được", "mai cũng được", "mai giao cũng không sao", "ngày mai giao cũng được", "tối giao cũng được",
        "chiều giao cũng được", "cuối giờ giao cũng được", "cuối tuần giao cũng được", "tuần này giao là được", "trong hôm nay là được",
        "khi nào tiện thì giao", "lúc nào rảnh thì mang qua", "rảnh thì giao", "tiện thì làm", "tiện lúc nào giao lúc đó",
        "không cần nhanh đâu", "không cần đi nhanh", "không cần giao ngay", "không cần ngay đâu", "chưa cần ngay", "chưa cần gấp đâu",
        "chưa cần tới ngay", "không cần ưu tiên đâu", "không cần hỏa tốc", "không cần khẩn trương đâu", "chẳng cần vội",
        "trễ chút cũng được", "trễ một chút không sao đâu", "muộn chút không sao", "muộn một chút cũng được", "chậm chút không sao",
        "đi chậm thôi cũng được", "chậm mà chắc", "không ai chờ cả", "không ai đợi đâu", "người nhận không gấp", "người nhận chưa cần",
        "bên nhận không vội", "không có hạn chót", "không có hạn giờ", "không giới hạn giờ giấc", "còn dư thời gian",
        "còn nhiều thì giờ", "thời gian còn dài", "thời gian thoải mái lắm", "đơn thường", "đơn bình thường thôi", "ưu tiên thấp",
        "mức ưu tiên thấp", "xếp sau cũng được", "làm sau cũng được", "để sau cũng không sao", "để lúc khác cũng được",
        "bình tĩnh mà đi", "cứ bình tĩnh nhé", "đi bình thường thôi", "tốc độ thường thôi", "nhẩn nha cũng được", "ung dung thôi",
        "không việc gì phải vội", "vội làm gì", "gấp gáp gì đâu", "có gì đâu mà gấp", "không đến mức gấp", "không quá gấp",
        "hết gấp rồi", "không còn gấp nữa", "giờ thì không gấp nữa", "no rush nhé", "không rush"],
    2: ["dễ vỡ nhé", "hàng dễ vỡ nhé", "đồ dễ vỡ đó", "rất dễ vỡ", "cực kỳ dễ vỡ", "dễ vỡ xin cẩn thận", "cẩn thận dễ vỡ",
        "hàng thủy tinh", "bên trong có thủy tinh", "có đồ thủy tinh", "chai thủy tinh bên trong", "lọ thủy tinh", "cốc thủy tinh",
        "bình thủy tinh", "ống nghiệm thủy tinh", "đồ gốm", "bình gốm", "đồ sứ dễ vỡ", "bát đĩa sứ", "chén sứ", "đồ pha lê dễ vỡ",
        "hàng mỏng manh lắm", "đồ mỏng manh", "rất mỏng manh", "hàng dễ hỏng", "dễ hỏng lắm", "dễ hư hỏng", "dễ hư", "dễ bể lắm",
        "dễ nứt vỡ", "dễ móp méo", "dễ gãy", "dễ trầy xước", "hàng dễ dập nát", "tránh va đập mạnh", "tránh va chạm mạnh",
        "tránh rung lắc mạnh", "tránh làm rơi", "đừng làm rơi nhé", "đừng để rơi", "không được rơi", "không được va đập",
        "không được lắc", "đừng lắc", "đừng rung mạnh", "đừng xóc", "đi nhẹ nhàng thôi", "đi nhẹ nhàng giúp", "nhẹ nhàng giúp mình",
        "nhẹ tay thôi nhé", "nhẹ tay giùm", "xin nhẹ tay", "cầm nhẹ nhàng", "nâng niu giúp mình", "giữ cẩn thận giúp", "cẩn thận nhé",
        "cẩn thận giúp mình", "hết sức cẩn thận", "cẩn thận kẻo bể", "cẩn thận kẻo rơi", "coi chừng bể", "coi chừng rơi vỡ",
        "kẻo bể", "kẻo hỏng", "vỡ là mất hết", "bể là hỏng", "hàng nhạy cảm", "thiết bị dễ hỏng", "thiết bị tinh vi dễ hỏng",
        "máy móc nhạy cảm", "linh kiện nhạy cảm", "màn hình dễ vỡ", "kính dễ vỡ", "có kính bên trong", "đồ điện tử dễ hỏng",
        "hàng cần đi êm", "đi êm thôi nhé", "đi thật êm", "chạy êm giúp", "giữ thăng bằng giúp", "đừng nghiêng", "không được nghiêng đổ",
        "giữ thẳng đứng", "hàng dễ đổ", "dễ đổ vỡ", "kỵ va chạm", "kỵ rơi", "sợ va đập", "sợ rơi vỡ", "fragile nhé", "hàng fragile"],
    4: ["không dễ vỡ đâu", "không dễ vỡ nhé", "hàng không dễ vỡ", "đồ không dễ vỡ", "chẳng dễ vỡ", "không vỡ được", "không vỡ đâu",
        "không sợ vỡ", "không lo bể", "không sợ bể", "không dễ hỏng", "không dễ hư", "khó hỏng lắm", "khó bể", "khó vỡ",
        "hàng chắc chắn lắm", "đồ chắc chắn", "rất chắc chắn", "hàng cứng", "đồ cứng cáp", "hàng bền", "đồ bền lắm", "bền lắm",
        "rất bền", "hàng lì đòn", "chịu va đập tốt", "chịu được va đập", "va đập không sao", "va chạm không sao", "rơi không sao",
        "rơi cũng được", "rơi không hỏng", "có rơi cũng không sao", "lỡ rơi cũng chẳng sao", "không sợ rơi vỡ", "không ngại va chạm",
        "không cần nhẹ tay đâu", "không cần nhẹ nhàng", "không cần cẩn thận lắm", "không cần nâng niu đâu", "khỏi cần nhẹ tay",
        "cứ thoải mái mà mang", "mạnh tay cũng được", "xóc cũng không sao", "lắc cũng không sao", "rung lắc thoải mái",
        "toàn giấy tờ thôi", "chỉ là giấy tờ", "toàn sách vở không vỡ", "đồ vải thôi", "toàn quần áo", "đồ nhựa không vỡ",
        "hàng khô", "hàng thường không dễ vỡ", "không phải đồ thủy tinh", "không có thủy tinh", "không có gì dễ hỏng",
        "không có đồ dễ vỡ", "bên trong không có gì dễ vỡ", "đóng gói rất kỹ rồi", "đã bọc chống sốc kỹ", "không mỏng manh gì"],
    0: ["hàng: thùng nước uống", "hàng: tập tài liệu", "hàng: hộp bút", "hàng: bưu kiện", "hàng là một hộp giấy", "món hàng là sách",
        "hàng cần giao là tập hồ sơ", "kiện hàng gồm hai hộp", "đơn gồm một túi đồ", "hàng nặng khoảng hai ký", "hàng nhẹ thôi",
        "hàng to, hơi cồng kềnh", "gói hàng nhỏ", "một thùng nhỏ", "cảm ơn nhé", "cảm ơn nhiều nha", "cảm ơn trước", "cám ơn robot nhiều",
        "thanks nhé", "thank you", "xin cảm ơn", "rất cảm ơn", "nhờ bạn", "nhờ robot nhé", "nhờ robot giúp", "phiền robot", "làm ơn giúp mình",
        "giúp mình với", "giúp mình nhé", "chào bạn", "chào robot nhé", "hello robot", "hi robot", "alo robot", "robot ơi giúp với",
        "có đơn mới", "đơn mới nè", "yêu cầu giao hàng", "yêu cầu mới đây", "thông báo đơn hàng", "nhiệm vụ mới", "nhiệm vụ giao hàng",
        "xác nhận giúp mình", "giao xong báo lại nhé", "tới nơi thì báo", "xong thì nhắn mình", "người nhận sẽ ra lấy", "người nhận tên Lan",
        "gọi người nhận khi tới", "để ở quầy lễ tân", "đặt trước cửa là được", "đưa tận tay người nhận", "nhớ lấy chữ ký", "ký nhận giúp",
        "đã thanh toán rồi", "không thu tiền", "miễn phí giao", "mã đơn ở trên", "số điện thoại ở trên bao bì", "chúc robot làm việc tốt",
        "chúc một ngày vui", "hẹn gặp sau", "vậy thôi nhé", "thế thôi", "hết rồi", "chỉ vậy thôi", "ok nhé", "được rồi đó", "tốt lắm",
        "trời hôm nay đẹp", "hôm nay đông người quá", "đường hơi đông", "nhớ đi đúng đường", "nhớ tuân thủ luật giao thông"],
}
